### PR TITLE
validate arguments given to getFoos

### PR DESCRIPTION
**Pull request by rjbs**
if we had been doing this to begin with, we would not have had
sinceState in there!

### CODE REVIEW

**Comment by rjbs** [comment]
This will require to code (which _does_ exist) that has entity types with their own args to get.  Also, we'll want to repeat this pattern for other `ix_method` methods.  Also, in the future we should compute per-rclass checkers at finalization time.

**Comment by wolfsage** [comment]
+1, though I wonder...

```
 unknownArguments => \@unknown,
```

Should we make this behave more like our property errors on ix_create/ix_get, where there's a key inside propertyErrors for each unknown property?

**Comment by rjbs** [comment]
Maybe!  Probably we can/should revisit this if/when we do things like barf on `getFoos => { ids => true }` and the like.  I still think there's a way to get Rx to do a lot of this work for us, somehow.

**Comment by rjbs** [comment]
Merged.

**Pull request closed without merging**
